import Foundation
import DeviceCheck
import CryptoKit

// MARK: - App Attest + Secure Enclave
// Proves requests come from a genuine, unmodified Box Fraise install.
// DCAppAttestService generates a key in the Secure Enclave and obtains
// Apple's signed attestation certificate. Each request carries an assertion
// proving it was generated by that key on this device.

@MainActor
final class AppAttest {
    static let shared = AppAttest()
    private init() {}

    private let keyIDKey    = "fraise_attest_key_id"
    private let attestedKey = "fraise_attest_done"

    var isSupported: Bool { DCAppAttestService.shared.isSupported }
    var keyID: String?    { UserDefaults.standard.string(forKey: keyIDKey) }
    var isAttested: Bool  { UserDefaults.standard.bool(forKey: attestedKey) }

    /// Call once after sign-in. No-op if already attested or running in simulator.
    func ensureAttestation(userToken: String?) async {
        guard isSupported, !isAttested else { return }
        do {
            let kid = try await getOrCreateKeyID()
            let challenge = Data(UUID().uuidString.utf8)
            let attestation = try await DCAppAttestService.shared.attestKey(
                kid, clientDataHash: Data(SHA256.hash(data: challenge))
            )
            try await APIClient.shared.registerAttestation(
                keyID: kid, attestation: attestation,
                challenge: challenge, userToken: userToken
            )
            UserDefaults.standard.set(true, forKey: attestedKey)
        } catch {
            // Non-fatal — HMAC signing continues as the request integrity layer
        }
    }

    /// Generate a per-request assertion. Returns nil on simulator or unattested devices.
    func assertion(for requestData: Data) async -> String? {
        guard isSupported, let kid = keyID else { return nil }
        let assertion = try? await DCAppAttestService.shared.generateAssertion(
            kid, clientDataHash: Data(SHA256.hash(data: requestData))
        )
        return assertion?.base64EncodedString()
    }

    private func getOrCreateKeyID() async throws -> String {
        if let kid = UserDefaults.standard.string(forKey: keyIDKey) { return kid }
        let kid = try await DCAppAttestService.shared.generateKey()
        UserDefaults.standard.set(kid, forKey: keyIDKey)
        return kid
    }
}
